
platform :ios, '13.0'

inhibit_all_warnings!

target 'MSIM-Swift' do
 
  use_frameworks!

  inhibit_all_warnings!
  
  pod 'Moya'
  pod 'lottie-ios'
  pod 'MJRefresh'
  pod 'Kingfisher'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'QCloudCOSXML/Transfer'
  pod 'ZLPhotoBrowser'

  pod 'MSIMSDK_DE4','1.3.6'
  
  ## 高德地图
  pod 'AMap3DMap'
  pod 'AMapSearch'

  pod 'AgoraRtcEngine_iOS'  #声网音视频聊天


end
