// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatProtobuf.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ChatItem;
@class ChatR;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ChatProtobufRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ChatProtobufRoot : GPBRootObject
@end

#pragma mark - ImToken

typedef GPB_ENUM(ImToken_FieldNumber) {
  ImToken_FieldNumber_Sign = 1,
  ImToken_FieldNumber_Token = 2,
};

/**
 * 0
 **/
GPB_FINAL @interface ImToken : GPBMessage

@property(nonatomic, readwrite) int64_t sign;

/** 设置token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - Ping

typedef GPB_ENUM(Ping_FieldNumber) {
  Ping_FieldNumber_Type = 1,
};

/**
 * 1
 **/
GPB_FINAL @interface Ping : GPBMessage

@property(nonatomic, readwrite) int64_t type;

@end

#pragma mark - Result

typedef GPB_ENUM(Result_FieldNumber) {
  Result_FieldNumber_Sign = 1,
  Result_FieldNumber_Code = 2,
  Result_FieldNumber_Msg = 3,
  Result_FieldNumber_NowTime = 4,
  Result_FieldNumber_Uid = 5,
};

/**
 * 2
 **/
GPB_FINAL @interface Result : GPBMessage

/** 信息标示，原路返回 */
@property(nonatomic, readwrite) int64_t sign;

@property(nonatomic, readwrite) int64_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

/** 当前服务器时间戳 */
@property(nonatomic, readwrite) int64_t nowTime;

/** 鉴权时返回的uid */
@property(nonatomic, readwrite) int64_t uid;

@end

#pragma mark - ChatS

typedef GPB_ENUM(ChatS_FieldNumber) {
  ChatS_FieldNumber_Sign = 1,
  ChatS_FieldNumber_Type = 2,
  ChatS_FieldNumber_ToUid = 3,
  ChatS_FieldNumber_Body = 4,
  ChatS_FieldNumber_Width = 5,
  ChatS_FieldNumber_Height = 6,
};

/**
 * 3
 **/
GPB_FINAL @interface ChatS : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 消息类型 */
@property(nonatomic, readwrite) int64_t type;

/** 发送给谁 */
@property(nonatomic, readwrite) int64_t toUid;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

/** 图片的宽度 */
@property(nonatomic, readwrite) int64_t width;

/** 图片的高度 */
@property(nonatomic, readwrite) int64_t height;

@end

#pragma mark - ChatSR

typedef GPB_ENUM(ChatSR_FieldNumber) {
  ChatSR_FieldNumber_Sign = 1,
  ChatSR_FieldNumber_MsgId = 2,
};

/**
 * 4
 **/
GPB_FINAL @interface ChatSR : GPBMessage

/** 信息标示，原路返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 消息id */
@property(nonatomic, readwrite) int64_t msgId;

@end

#pragma mark - ChatR

typedef GPB_ENUM(ChatR_FieldNumber) {
  ChatR_FieldNumber_MsgId = 1,
  ChatR_FieldNumber_FromUid = 2,
  ChatR_FieldNumber_Type = 3,
  ChatR_FieldNumber_Body = 4,
  ChatR_FieldNumber_Width = 5,
  ChatR_FieldNumber_Height = 6,
};

/**
 * 5
 **/
GPB_FINAL @interface ChatR : GPBMessage

/** 消息id */
@property(nonatomic, readwrite) int64_t msgId;

/** 谁发的 */
@property(nonatomic, readwrite) int64_t fromUid;

/** 消息类型 */
@property(nonatomic, readwrite) int64_t type;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

/** 图片的宽度 */
@property(nonatomic, readwrite) int64_t width;

/** 图片的高度 */
@property(nonatomic, readwrite) int64_t height;

@end

#pragma mark - ChatRbatch

typedef GPB_ENUM(ChatRbatch_FieldNumber) {
  ChatRbatch_FieldNumber_Sign = 1,
  ChatRbatch_FieldNumber_MsgsArray = 2,
};

/**
 * 6
 **/
GPB_FINAL @interface ChatRbatch : GPBMessage

/** 信息标示，原路返回 */
@property(nonatomic, readwrite) int64_t sign;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChatR*> *msgsArray;
/** The number of items in @c msgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@end

#pragma mark - GetHistory

typedef GPB_ENUM(GetHistory_FieldNumber) {
  GetHistory_FieldNumber_Sign = 1,
  GetHistory_FieldNumber_ToUid = 2,
  GetHistory_FieldNumber_MsgId = 3,
  GetHistory_FieldNumber_Offset = 4,
};

/**
 * 7
 **/
GPB_FINAL @interface GetHistory : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 和谁的聊天记录 */
@property(nonatomic, readwrite) int64_t toUid;

/** msg id 指针 */
@property(nonatomic, readwrite) int64_t msgId;

/** 拉多少条，默认20，最多100 */
@property(nonatomic, readwrite) int64_t offset;

@end

#pragma mark - Revoke

typedef GPB_ENUM(Revoke_FieldNumber) {
  Revoke_FieldNumber_Sign = 1,
  Revoke_FieldNumber_ToUid = 2,
  Revoke_FieldNumber_MsgId = 3,
};

/**
 * 8
 **/
GPB_FINAL @interface Revoke : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 谁发的消息 */
@property(nonatomic, readwrite) int64_t toUid;

/** 撤回的消息id */
@property(nonatomic, readwrite) int64_t msgId;

@end

#pragma mark - MsgRead

typedef GPB_ENUM(MsgRead_FieldNumber) {
  MsgRead_FieldNumber_Sign = 1,
  MsgRead_FieldNumber_ToUid = 2,
  MsgRead_FieldNumber_MsgId = 3,
};

/**
 * 9
 **/
GPB_FINAL @interface MsgRead : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 谁发的消息已读 */
@property(nonatomic, readwrite) int64_t toUid;

/** 已读消息id */
@property(nonatomic, readwrite) int64_t msgId;

@end

#pragma mark - LastReadMsg

typedef GPB_ENUM(LastReadMsg_FieldNumber) {
  LastReadMsg_FieldNumber_FromUid = 1,
  LastReadMsg_FieldNumber_MsgId = 2,
  LastReadMsg_FieldNumber_Unread = 3,
};

/**
 * 10 消息已读状态发生变更通知（客户端收到这个才去变更）
 **/
GPB_FINAL @interface LastReadMsg : GPBMessage

/** 谁的会话 */
@property(nonatomic, readwrite) int64_t fromUid;

/** 最后一条已读消息 */
@property(nonatomic, readwrite) int64_t msgId;

/** 还有多少条未读消息 */
@property(nonatomic, readwrite) int64_t unread;

@end

#pragma mark - DelChat

typedef GPB_ENUM(DelChat_FieldNumber) {
  DelChat_FieldNumber_Sign = 1,
  DelChat_FieldNumber_ToUid = 2,
};

/**
 * 11
 **/
GPB_FINAL @interface DelChat : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 删除谁的 */
@property(nonatomic, readwrite) int64_t toUid;

@end

#pragma mark - GetChatList

typedef GPB_ENUM(GetChatList_FieldNumber) {
  GetChatList_FieldNumber_Sign = 1,
  GetChatList_FieldNumber_MsgId = 2,
};

/**
 * 12
 **/
GPB_FINAL @interface GetChatList : GPBMessage

/** 客户端自定义标识，服务器会原样返回 */
@property(nonatomic, readwrite) int64_t sign;

/** 客户端本地保存的会话列表的最新一个会话的msg id */
@property(nonatomic, readwrite) int64_t msgId;

@end

#pragma mark - ChatItem

typedef GPB_ENUM(ChatItem_FieldNumber) {
  ChatItem_FieldNumber_Uid = 1,
  ChatItem_FieldNumber_MsgStart = 2,
  ChatItem_FieldNumber_MsgEnd = 3,
  ChatItem_FieldNumber_LastMsg = 4,
  ChatItem_FieldNumber_Unread = 5,
  ChatItem_FieldNumber_IsNew = 6,
  ChatItem_FieldNumber_MyMove = 7,
  ChatItem_FieldNumber_IceBreak = 8,
  ChatItem_FieldNumber_TipFree = 9,
};

/**
 * 13
 **/
GPB_FINAL @interface ChatItem : GPBMessage

@property(nonatomic, readwrite) int64_t uid;

@property(nonatomic, readwrite) int64_t msgStart;

@property(nonatomic, readwrite) int64_t msgEnd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastMsg;

@property(nonatomic, readwrite) int64_t unread;

@property(nonatomic, readwrite) BOOL isNew;

@property(nonatomic, readwrite) BOOL myMove;

@property(nonatomic, readwrite) BOOL iceBreak;

@property(nonatomic, readwrite) BOOL tipFree;

@end

#pragma mark - ChatList

typedef GPB_ENUM(ChatList_FieldNumber) {
  ChatList_FieldNumber_ChatItemsArray = 1,
};

/**
 * 14
 **/
GPB_FINAL @interface ChatList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChatItem*> *chatItemsArray;
/** The number of items in @c chatItemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger chatItemsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
